### ISSUE TITLE
How to print a euro sign

### ISSUE THREAD

**Issue by craftyweb** [vadavo/NEscPos#6]
Hello I'm trying to make a receipt so I want to display the total with a euro sign. But when I try to insert it, it shows up as ?. 

How can I fix this?

Thanks in advance!

**Comment by craftyweb** [comment]
It was something in my printer settings. I will close this issue

**Comment by montyclt** [comment]
Hello @craftyweb!
I am glad that you have solved it. Can I ask about your printer model?

This project is currently paused (not abandoned). We have plans to continue it on 2021. I sugest you see and compare with this other project. https://github.com/lukevp/ESC-POS-.NET
